/**
 * Capital Operator — Markdown & Clipboard Export Formatter
 * src/lib/export.ts
 */

import { BlueprintResult } from '../types';

export function formatBlueprintAsMarkdown(blueprint: BlueprintResult): string {
  const dateStr = new Date().toLocaleDateString('en-US', {
    month: 'long',
    day: 'numeric',
    year: 'numeric'
  });

  return `# Capital Operator — Capital Infrastructure Blueprint
**Generated:** ${dateStr}
**Current Operating Model:** ${blueprint.operatingModel}
**Next Capability Unlock:** ${blueprint.nextUnlock}

---

## Executive Summary
${blueprint.executiveSummary}

## Top Finding
**${blueprint.topFindingHeadline}**

## Highest-Leverage Move
- **Target:** ${blueprint.highestLeverageMove.headline}
- **Objective:** ${blueprint.highestLeverageMove.subheadline}
- **Action Plan:** ${blueprint.highestLeverageMove.action}

---

## 8-Stage Operating Architecture & Recommended Stack

${blueprint.stages
  .map(
    (s) => `### Stage ${s.stageNumber}: ${s.stageName} [${s.priority}]
- **Capability Needed:** ${s.capabilityNeeded}
- **Primary Tool:** ${s.primaryTool.name} (${s.primaryTool.pricingTier}) — ${s.primaryTool.websiteUrl}
- **Operational Drag:** ${s.currentFriction}
- **System Handles:** ${s.systemHandles}
- **Human Judgment Checkpoint:** ${s.judgmentMatters}`
  )
  .join('\n\n')}

---

## Operational Leaks & Vulnerabilities
${blueprint.automationLeaks
  .map(
    (leak, idx) => `${idx + 1}. **${leak.currentWork}** [${leak.urgency} URGENCY]
   - *System Solution:* ${leak.systemHandles}
   - *Business Impact:* ${leak.businessImpact}`
  )
  .join('\n\n')}

---

## 30-Day Implementation Roadmap

### First 7 Days
${blueprint.roadmap.first7Days.map((i) => `- **Step ${i.step}: ${i.title}** (${i.stageLabel || 'Foundational'})\n  ${i.description}`).join('\n')}

### Next 30 Days
${blueprint.roadmap.next30Days.map((i) => `- **Step ${i.step}: ${i.title}** (${i.stageLabel || 'Execution'})\n  ${i.description}`).join('\n')}

### Later (Compounding)
${blueprint.roadmap.later.map((i) => `- **Step ${i.step}: ${i.title}** (${i.stageLabel || 'Scale'})\n  ${i.description}`).join('\n')}

---
*Generated by Capital Operator — Moonshine Capital (https://moonshinecapital.io)*
`;
}

export async function copyBlueprintToClipboard(blueprint: BlueprintResult): Promise<boolean> {
  try {
    const md = formatBlueprintAsMarkdown(blueprint);
    await navigator.clipboard.writeText(md);
    return true;
  } catch (err) {
    console.warn('Clipboard write failed:', err);
    return false;
  }
}
