/**
 * Capital Operator — Canonical Analytics Event Definitions (C2 Reconciled)
 * src/config/analyticsEvents.ts
 */

export const ANALYTICS_EVENTS = {
  PAGE_VIEW: 'page_view',
  ASSESSMENT_STARTED: 'capital_operator_started',
  ASSESSMENT_STEP_COMPLETED: 'assessment_step_completed',
  ASSESSMENT_COMPLETED: 'assessment_completed',
  BLUEPRINT_GENERATED: 'blueprint_generated',
  BLUEPRINT_COPIED: 'blueprint_copied',
  BLUEPRINT_PRINTED: 'blueprint_printed',
  CAPABILITY_VIEWED: 'capability_viewed',
  TOOL_CLICKED: 'tool_clicked',
  AFFILIATE_CLICKED: 'affiliate_clicked',
  MOONSHINE_ASSET_CLICKED: 'moonshine_asset_clicked',
  LEAD_SUBMITTED: 'lead_submitted',
  PARTNER_CTA_CLICKED: 'partner_cta_clicked',
  FUNDING_CTA_CLICKED: 'funding_cta_clicked',
  DEAL_CTA_CLICKED: 'deal_cta_clicked',
  CTA_ACTION: 'cta_action',
  MARKETING_CTA_CLICK: 'marketing_cta_click',
  SECTION_VIEW: 'section_view',
  INTEGRATION_VIEWED: 'integration_viewed',
  EMBED_COPIED: 'embed_copied',
  ECOSYSTEM_PRODUCT_CLICKED: 'ecosystem_product_clicked',
  ECOSYSTEM_RECOMMENDATION_GENERATED: 'ecosystem_recommendation_generated',
  CAPABILITY_MATCHED: 'capability_matched',
  DOWNSTREAM_PRODUCT_RECOMMENDED: 'downstream_product_recommended',
  ECOSYSTEM_HANDOFF_INITIATED: 'ecosystem_handoff_initiated',
  ECOSYSTEM_HANDOFF_COMPLETED: 'ecosystem_handoff_completed',
  ECOSYSTEM_FALLBACK_USED: 'ecosystem_fallback_used',
  ARCHITECTURE_MAP_NODE_CLICKED: 'architecture_map_node_clicked',
  SITUATION_SELECTED: 'situation_selected',
  ASSESSMENT_RESTARTED: 'assessment_restarted',
  API_REQUEST: 'api_request',
  API_SUCCESS: 'api_success',
  API_FAILURE: 'api_failure',
  ROUTING_COMPLETED: 'routing_completed',
  INTEGRATION_DISPATCHED: 'integration_dispatched',
  INTEGRATION_FAILED: 'integration_failed',
  WEBHOOK_DISPATCHED: 'webhook_dispatched',
  WEBHOOK_FAILED: 'webhook_failed',
  PUBLIC_TOOL_VIEWED: 'public_tool_viewed',
  PUBLIC_TOOL_STARTED: 'public_tool_started',
  PUBLIC_TOOL_COMPLETED: 'public_tool_completed',
  PUBLIC_TOOL_RESULT_GENERATED: 'public_tool_result_generated',
  PUBLIC_TOOL_CTA_CLICKED: 'public_tool_cta_clicked',
  PUBLIC_TOOL_SHARED: 'public_tool_shared',
  PUBLIC_TOOL_LEAD_HANDOFF_STARTED: 'public_tool_lead_handoff_started',
  PUBLIC_TOOL_LEAD_HANDOFF_COMPLETED: 'public_tool_lead_handoff_completed',
  // C2 Knowledge & Entity Layer Analytics Events
  KNOWLEDGE_PAGE_VIEWED: 'knowledge_page_viewed',
  KNOWLEDGE_RELATED_TOOL_CLICKED: 'knowledge_related_tool_clicked',
  KNOWLEDGE_RELATED_ENTITY_CLICKED: 'knowledge_related_entity_clicked',
  WORKFLOW_STAGE_VIEWED: 'workflow_stage_viewed',
  OPERATING_MODEL_VIEWED: 'operating_model_viewed',
  OPERATING_MODEL_EVOLUTION_CLICKED: 'operating_model_evolution_clicked',
  LEARN_TO_TOOL_HANDOFF: 'learn_to_tool_handoff',
  LEARN_TO_ECOSYSTEM_HANDOFF: 'learn_to_ecosystem_handoff',
  FUNDING_SEARCH_STARTED: 'funding_search_started',
  FUNDING_OPTIONS_GENERATED: 'funding_options_generated',
  PROVIDER_CANDIDATE_VIEWED: 'provider_candidate_viewed',
  PRODUCT_CANDIDATE_VIEWED: 'product_candidate_viewed',
  DOCUMENT_CHECKLIST_GENERATED: 'document_checklist_generated',
  SUPPORT_TOOL_RECOMMENDED: 'support_tool_recommended',
  FUNDING_HANDOFF_PREPARED: 'funding_handoff_prepared',
  GET_FUNDED_STARTED: 'get_funded_started',
  GET_FUNDED_COMPLETED: 'get_funded_completed'
} as const;

export type AnalyticsEventName = typeof ANALYTICS_EVENTS[keyof typeof ANALYTICS_EVENTS];
