/**
 * Capital Operator — Central Tool Registry
 * src/config/tools.ts
 */

import { ToolItem } from '../types';

export const TOOLS_REGISTRY: Record<string, ToolItem> = {
  // === INTAKE & DEMAND GENERATION ===
  tally: {
    id: 'tally',
    name: 'Tally Forms',
    category: 'intake',
    workflowStage: 2,
    description: 'Clean, frictionless conditional intake builder with webhook and CRM sync support.',
    bestFor: 'Multi-step borrower intake, partner referral forms, and fast conditional data capture.',
    notFor: 'Full document extraction or lender underwriting.',
    pricingTier: 'Free / Low',
    websiteUrl: 'https://tally.so',
    affiliateUrl: 'https://tally.so?ref=moonshine',
    isAffiliate: true,
    moonshineAsset: false,
    capability: 'Structured funding intake & qualification logic',
    aiRole: 'Validate completeness and pre-populate borrower profile fields via webhook',
    humanRole: 'Review submissions and interpret deal narrative',
    alternatives: ['jotform_agents', 'hubspot'],
    tags: ['Intake', 'Forms', 'No-Code']
  },

  jotform_agents: {
    id: 'jotform_agents',
    name: 'Jotform AI Agents',
    category: 'intake',
    workflowStage: 2,
    description: 'Interactive conversational intake agent that guides business owners through missing questions.',
    bestFor: 'Dynamic intake for variable business profiles without overwhelming with a 40-field form.',
    notFor: 'Replacing formal lender credit boxes.',
    pricingTier: 'Mid ($50-$250)',
    websiteUrl: 'https://www.jotform.com',
    isAffiliate: false,
    moonshineAsset: false,
    capability: 'Conversational intake & guided form completion',
    aiRole: 'Prompt for missing financial facts and summarize borrower use case',
    humanRole: 'Ensure applicant was not promised approval by conversational interface',
    alternatives: ['tally', 'retell_ai'],
    tags: ['Intake', 'Conversational', 'AI']
  },

  apollo: {
    id: 'apollo',
    name: 'Apollo.io',
    category: 'research',
    workflowStage: 1,
    description: 'B2B data enrichment and account signal prospecting engine for commercial funding outreach.',
    bestFor: 'Niche account identification, owner contact data, and industry segment verification.',
    notFor: 'Pipeline management or document storage.',
    pricingTier: 'Mid ($50-$250)',
    websiteUrl: 'https://apollo.io',
    isAffiliate: false,
    moonshineAsset: false,
    capability: 'Targeted account acquisition & contact verification',
    aiRole: 'Surface trigger events (growth, UCC filings, hiring) indicating capital need',
    humanRole: 'Confirm market fit and message credibility before outreach',
    alternatives: ['clay', 'zoominfo'],
    tags: ['Prospecting', 'Data', 'Enrichment']
  },

  clay: {
    id: 'clay',
    name: 'Clay',
    category: 'research',
    workflowStage: 1,
    description: 'Programmable data enrichment platform combining 50+ sources with AI research prompts.',
    bestFor: 'Deep company research, revenue estimates, and customized qualification waterfalls.',
    notFor: 'Direct customer-facing applications.',
    pricingTier: 'Pro ($250-$750)',
    websiteUrl: 'https://clay.com',
    isAffiliate: false,
    moonshineAsset: false,
    capability: 'Automated business enrichment & pre-qualification data',
    aiRole: 'Cascade company websites, state registry, and public records into a clean dossier',
    humanRole: 'Set enrichment boundaries and filter false-positive leads',
    alternatives: ['apollo', 'perplexity'],
    tags: ['Enrichment', 'Waterfalls', 'AI Research']
  },

  // === CRM & WORKFLOW ORCHESTRATION ===
  hubspot: {
    id: 'hubspot',
    name: 'HubSpot CRM + Breeze',
    category: 'CRM',
    workflowStage: 2,
    description: 'Central capital system of record with native workflow automation, pipeline stages, and AI assistance.',
    bestFor: 'Active deal pipelines, multi-operator deal desk coordination, and audit-ready tracking.',
    notFor: 'Standalone document OCR or lender credit decisioning.',
    pricingTier: 'Mid ($50-$250)',
    websiteUrl: 'https://hubspot.com',
    isAffiliate: false,
    moonshineAsset: false,
    capability: 'Central deal operating system & automated pipeline staging',
    aiRole: 'Summarize deal notes, prioritize stale opportunities, and draft stage updates',
    humanRole: 'Ownership of lender relationships, deal structuring, and final approvals',
    alternatives: ['notion_ops', 'salesforce'],
    tags: ['CRM', 'Pipeline', 'Operating Core']
  },

  notion_ops: {
    id: 'notion_ops',
    name: 'Notion Database + AI',
    category: 'CRM',
    workflowStage: 2,
    description: 'Flexible operating workspace for solo operators, lender matrices, SOPs, and deal tracking.',
    bestFor: 'Solo brokers, startup capital teams, and governed internal lender playbooks.',
    notFor: 'High-volume 500+ deal per month call center distribution.',
    pricingTier: 'Free / Low',
    websiteUrl: 'https://notion.so',
    isAffiliate: false,
    moonshineAsset: false,
    capability: 'Lightweight deal pipeline & structured lender matrix',
    aiRole: 'Draft review memos, extract meeting summaries, and search internal playbooks',
    humanRole: 'Maintain matrix accuracy and manually verify guideline freshness',
    alternatives: ['airtable_ops', 'hubspot'],
    tags: ['Workspace', 'Matrix', 'Solo Stack']
  },

  airtable_ops: {
    id: 'airtable_ops',
    name: 'Airtable Operating Base',
    category: 'CRM',
    workflowStage: 5,
    description: 'Relational deal database with formula-based lender matching and automated status triggers.',
    bestFor: 'Multi-criteria credit box filtering, document checklists, and submission queues.',
    notFor: 'Consumer borrower direct portal.',
    pricingTier: 'Mid ($50-$250)',
    websiteUrl: 'https://airtable.com',
    isAffiliate: false,
    moonshineAsset: false,
    capability: 'Governed lender-fit matching matrix & deal state engine',
    aiRole: 'Compare borrower stats against lender requirements to produce shortlist',
    humanRole: 'Determine exception likelihood and choose submission sequence',
    alternatives: ['notion_ops', 'hubspot'],
    tags: ['Database', 'Lender Matrix', 'Routing']
  },

  n8n: {
    id: 'n8n',
    name: 'n8n Workflow Automation',
    category: 'workflow automation',
    workflowStage: 6,
    description: 'Self-hostable or cloud visual workflow engine capable of combining APIs, webhooks, and AI agents.',
    bestFor: 'Complex multi-step deal packaging, CRM syncing, webhook routers, and secure data pipelines.',
    notFor: 'Non-technical operators wanting zero setup.',
    pricingTier: 'Free / Low',
    websiteUrl: 'https://n8n.io',
    isAffiliate: false,
    moonshineAsset: false,
    capability: 'Full-stack workflow orchestration & secure API bridge',
    aiRole: 'Execute multi-step data parsing, validation rules, and automated formatting',
    humanRole: 'Define trigger conditions, security boundaries, and exception queues',
    alternatives: ['make', 'zapier'],
    tags: ['Automation', 'APIs', 'Orchestration']
  },

  make: {
    id: 'make',
    name: 'Make.com',
    category: 'workflow automation',
    workflowStage: 6,
    description: 'Visual integration platform connecting forms, CRM, email, and storage without code.',
    bestFor: 'Fast connector between Tally, HubSpot, Google Drive, and notification webhooks.',
    notFor: 'High-security self-hosted banking servers.',
    pricingTier: 'Free / Low',
    websiteUrl: 'https://make.com',
    affiliateUrl: 'https://make.com?ref=moonshine',
    isAffiliate: true,
    moonshineAsset: false,
    capability: 'No-code event orchestration & deal handoffs',
    aiRole: 'Route data payloads between systems on status changes',
    humanRole: 'Oversee execution logs and resolve data mismatch errors',
    alternatives: ['n8n', 'zapier'],
    tags: ['Automation', 'Visual', 'No-Code']
  },

  zapier: {
    id: 'zapier',
    name: 'Zapier',
    category: 'workflow automation',
    workflowStage: 6,
    description: 'Everywhere-integrated automation platform for quick point-to-point triggers.',
    bestFor: 'Simple 2-step triggers (e.g. Form submitted -> send Slack alert + create CRM record).',
    notFor: 'Complex conditional branching at high scale.',
    pricingTier: 'Mid ($50-$250)',
    websiteUrl: 'https://zapier.com',
    isAffiliate: false,
    moonshineAsset: false,
    capability: 'Point-to-point triggers & instant team notifications',
    aiRole: 'Instant data copy and timestamping',
    humanRole: 'Act on notification alerts immediately',
    alternatives: ['make', 'n8n'],
    tags: ['Automation', 'Triggers']
  },

  // === DOCUMENT INTELLIGENCE & FINANCIAL DATA ===
  ocrolus: {
    id: 'ocrolus',
    name: 'Ocrolus',
    category: 'document intelligence',
    workflowStage: 4,
    description: 'Fintech infrastructure for automated financial document verification, bank statement OCR, and cash-flow analytics.',
    bestFor: 'High-volume bank statement analysis, revenue validation, and detecting tampered PDFs.',
    notFor: 'Casual solo operators handling 3 deals a month.',
    pricingTier: 'Enterprise ($750+)',
    websiteUrl: 'https://ocrolus.com',
    isAffiliate: false,
    moonshineAsset: false,
    capability: 'Bank statement analysis, fraud detection & cash flow metric extraction',
    aiRole: 'Extract exact average monthly deposits, negative days, and calculate true cash flow',
    humanRole: 'Interpret seasonal revenue dips and negotiate with lender underwriters',
    alternatives: ['heron_data', 'docsumo'],
    tags: ['Documents', 'OCR', 'Cash Flow', 'Underwriting']
  },

  heron_data: {
    id: 'heron_data',
    name: 'Heron Data',
    category: 'document intelligence',
    workflowStage: 4,
    description: 'Commercial lending document processing engine designed specifically for loan brokers and originators.',
    bestFor: 'Categorizing bank transaction data, debt detection, and verifying true debt service coverage.',
    notFor: 'Non-financial general document storage.',
    pricingTier: 'Pro ($250-$750)',
    websiteUrl: 'https://herondata.io',
    isAffiliate: false,
    moonshineAsset: false,
    capability: 'Automated debt stacking detection & borrower cash-flow summary',
    aiRole: 'Isolate active MCA / loan payments and calculate debt service obligations',
    humanRole: 'Review debt payoff requirements and structure consolidation options',
    alternatives: ['ocrolus', 'validis'],
    tags: ['Fintech', 'Debt Detection', 'Bank Statements']
  },

  docsumo: {
    id: 'docsumo',
    name: 'Docsumo',
    category: 'document collection',
    workflowStage: 4,
    description: 'AI-powered document extraction for tax returns, P&L statements, and invoices.',
    bestFor: 'Tax return extraction, commercial invoices, and financial statement validation.',
    notFor: 'Complete CRM pipeline workflows.',
    pricingTier: 'Mid ($50-$250)',
    websiteUrl: 'https://docsumo.com',
    isAffiliate: false,
    moonshineAsset: false,
    capability: 'Intelligent document extraction & tax return digitization',
    aiRole: 'Digitize multi-page 1120-S and 1040 forms into verified structured key-value data',
    humanRole: 'Validate depreciation add-backs and discretionary earnings',
    alternatives: ['ocrolus', 'heron_data'],
    tags: ['OCR', 'Tax Returns', 'Extraction']
  },

  validis: {
    id: 'validis',
    name: 'Validis',
    category: 'financial data',
    workflowStage: 4,
    description: 'Direct accounting software extraction (QuickBooks, Xero, NetSuite) for commercial lending verification.',
    bestFor: 'Mid-market business loans requiring audit-quality balance sheets and trial balances.',
    notFor: 'Micro-ticket revenue advances.',
    pricingTier: 'Enterprise ($750+)',
    websiteUrl: 'https://validis.com',
    isAffiliate: false,
    moonshineAsset: false,
    capability: 'Accounting system direct sync & standardized financial statements',
    aiRole: 'Map divergent chart of accounts into standardized lender presentation format',
    humanRole: 'Explain accounting anomalies directly to senior credit committee',
    alternatives: ['heron_data', 'ocrolus'],
    tags: ['Accounting', 'QuickBooks Sync', 'Financials']
  },

  // === RESEARCH & ANALYSIS ===
  perplexity: {
    id: 'perplexity',
    name: 'Perplexity Enterprise',
    category: 'research',
    workflowStage: 3,
    description: 'Cited web search and market research intelligence for real-time company analysis.',
    bestFor: 'Verifying company reputational signals, license statuses, litigation, and market context.',
    notFor: 'Internal secure borrower document processing.',
    pricingTier: 'Free / Low',
    websiteUrl: 'https://perplexity.ai',
    isAffiliate: false,
    moonshineAsset: false,
    capability: 'Real-time commercial intelligence & business background research',
    aiRole: 'Compile cited briefing on operating footprint, web reputation, and industry trends',
    humanRole: 'Verify high-friction flags and incorporate context into lender executive summary',
    alternatives: ['claude_ai', 'chatgpt'],
    tags: ['Research', 'Due Diligence', 'Intelligence']
  },

  claude_ai: {
    id: 'claude_ai',
    name: 'Claude 3.7 Sonnet / Opus',
    category: 'research',
    workflowStage: 4,
    description: 'Advanced reasoning model with 200k context window for analyzing complex loan packages and term sheets.',
    bestFor: 'Synthesizing 50-page financial files, drafting lender submission memos, and comparing term sheets.',
    notFor: 'Autonomous decision-making without human review.',
    pricingTier: 'Free / Low',
    websiteUrl: 'https://anthropic.com',
    isAffiliate: false,
    moonshineAsset: false,
    capability: 'Deal narrative synthesis, anomaly detection & credit memo drafting',
    aiRole: 'Draft objective credit narrative linking use of funds to debt service ability',
    humanRole: 'Mandatory verification of every financial figure and final sign-off',
    alternatives: ['chatgpt', 'perplexity'],
    tags: ['AI Reasoning', 'Credit Memo', 'Synthesis']
  },

  chatgpt: {
    id: 'chatgpt',
    name: 'ChatGPT Enterprise / Team',
    category: 'research',
    workflowStage: 4,
    description: 'Custom GPTs and assistants for internal deal triage, policy Q&A, and client messaging.',
    bestFor: 'Internal team copilots, quick borrower correspondence, and formula generation.',
    notFor: 'Direct submission to lenders without strict human verification.',
    pricingTier: 'Free / Low',
    websiteUrl: 'https://openai.com',
    isAffiliate: false,
    moonshineAsset: false,
    capability: 'Internal deal desk copilot & contextual communication drafting',
    aiRole: 'Generate customized document request lists and question checklists',
    humanRole: 'Approve all borrower-facing and lender-facing messages',
    alternatives: ['claude_ai', 'perplexity'],
    tags: ['Copilot', 'Drafting', 'General AI']
  },

  // === COMMUNICATION & FOLLOW-UP ===
  fireflies: {
    id: 'fireflies',
    name: 'Fireflies.ai',
    category: 'call intelligence',
    workflowStage: 7,
    description: 'Automated meeting transcription, action item extraction, and CRM note generation.',
    bestFor: 'Discovery calls, borrower interviews, and lender rep conversations.',
    notFor: 'Cold calling dialers.',
    pricingTier: 'Free / Low',
    websiteUrl: 'https://fireflies.ai',
    isAffiliate: false,
    moonshineAsset: false,
    capability: 'Call transcription, commitment extraction & CRM auto-logging',
    aiRole: 'Extract stated revenue, owner goals, use of funds, and required follow-up dates',
    humanRole: 'Confirm commitments made on the call and maintain personal trust',
    alternatives: ['gong'],
    tags: ['Call Recording', 'Action Items', 'Transcription']
  },

  gong: {
    id: 'gong',
    name: 'Gong.io',
    category: 'call intelligence',
    workflowStage: 7,
    description: 'Enterprise revenue intelligence analyzing conversation sentiment, deal risk, and pipeline velocity.',
    bestFor: 'Teams with 5+ brokers managing high deal volume where pipeline leakage is critical.',
    notFor: 'Solo brokers on tight budgets.',
    pricingTier: 'Enterprise ($750+)',
    websiteUrl: 'https://gong.io',
    isAffiliate: false,
    moonshineAsset: false,
    capability: 'Deal velocity tracking & objection analysis across originators',
    aiRole: 'Flag when borrower engagement drops or competitor financing is mentioned',
    humanRole: 'Step in on high-value at-risk transactions to save the placement',
    alternatives: ['fireflies'],
    tags: ['Enterprise', 'Revenue Intelligence']
  },

  retell_ai: {
    id: 'retell_ai',
    name: 'Retell AI Voice Agents',
    category: 'call intelligence',
    workflowStage: 2,
    description: 'Ultra-low latency conversational voice agents for after-hours scheduling and preliminary intake.',
    bestFor: 'Instant speed-to-lead outbound calls to web form submissions for scheduling.',
    notFor: 'Complex credit structuring or negotiating loan covenants.',
    pricingTier: 'Mid ($50-$250)',
    websiteUrl: 'https://retellai.com',
    isAffiliate: false,
    moonshineAsset: false,
    capability: 'Voice agent speed-to-lead & discovery call scheduling',
    aiRole: 'Engage web inquiries within 60 seconds, verify basic facts, and schedule broker discovery',
    humanRole: 'Conduct the actual substantive financial strategy conversation',
    alternatives: ['jotform_agents', 'fireflies'],
    tags: ['Voice AI', 'Speed to Lead', 'Scheduling']
  },

  // === MOONSHINE CAPITAL ECOSYSTEM ASSETS ===
  am_i_fundable: {
    id: 'am_i_fundable',
    name: 'Am I Fundable',
    category: 'underwriting support',
    workflowStage: 2,
    description: 'Moonshine Capital funding readiness diagnostic screening business cash flow, entity age, and credit signals.',
    bestFor: 'Preliminary pre-qualification triage before requesting sensitive financial documents.',
    notFor: 'Binding lender underwriting decisions.',
    pricingTier: 'Free / Low',
    websiteUrl: 'https://tools.distilledfunding.com',
    isAffiliate: false,
    moonshineAsset: true,
    capability: 'Borrower funding readiness assessment & friction mapping',
    aiRole: 'Calculate preliminary capital category fit and identify missing baseline data',
    humanRole: 'Determine whether file is ready for underwriting or needs credit preparation first',
    alternatives: ['fundready_copilot'],
    tags: ['Moonshine Ecosystem', 'Readiness', 'Pre-Qual']
  },

  fundready_copilot: {
    id: 'fundready_copilot',
    name: 'FundReady Copilot',
    category: 'underwriting support',
    workflowStage: 2,
    description: 'Operational assistant that evaluates applicant data against standard commercial funding boxes.',
    bestFor: 'Advisors and consultants screening client funding requests before making partner referrals.',
    notFor: 'Final lender approvals.',
    pricingTier: 'Mid ($50-$250)',
    websiteUrl: 'https://tools.distilledfunding.com',
    isAffiliate: false,
    moonshineAsset: true,
    capability: 'Automated deal eligibility screening & gap identification',
    aiRole: 'Compare stated revenue and time in business against credit boxes to highlight roadblocks',
    humanRole: 'Explain necessary preparation steps to the client to preserve trust',
    alternatives: ['am_i_fundable'],
    tags: ['Moonshine Ecosystem', 'Eligibility', 'Copilot']
  },

  fundstack_ai: {
    id: 'fundstack_ai',
    name: 'FundStack AI',
    category: 'capital matching',
    workflowStage: 5,
    description: 'Central capital navigation layer organizing product families, routing rules, and partner attribution.',
    bestFor: 'Originators managing multiple product types (Working Capital, SBA, Equipment, LOC, Real Estate).',
    notFor: 'Direct retail consumer lending.',
    pricingTier: 'Mid ($50-$250)',
    websiteUrl: 'https://tools.distilledfunding.com',
    isAffiliate: false,
    moonshineAsset: true,
    capability: 'Multi-family capital navigation & governed partner routing',
    aiRole: 'Shortlist top 3 product families based on business profile signals',
    humanRole: 'Final submission decision and relationship management',
    alternatives: ['lender_fit_copilot'],
    tags: ['Moonshine Ecosystem', 'Routing', 'Product Families']
  },

  lender_fit_copilot: {
    id: 'lender_fit_copilot',
    name: 'Lender Fit Routing Copilot',
    category: 'capital matching',
    workflowStage: 5,
    description: 'Dynamic lender matching copilot comparing borrower metrics against current partner appetite.',
    bestFor: 'Selecting exact institutional lender paths without relying on broker memory.',
    notFor: 'Automated blind submission without human signoff.',
    pricingTier: 'Mid ($50-$250)',
    websiteUrl: 'https://tools.distilledfunding.com',
    isAffiliate: false,
    moonshineAsset: true,
    capability: 'Credit-box rule evaluation & lender shortlist rationale',
    aiRole: 'Generate shortlist rationale highlighting matching guidelines and potential friction points',
    humanRole: 'Verify lender relationship nuance, current queue times, and submission order',
    alternatives: ['fundstack_ai', 'airtable_ops'],
    tags: ['Moonshine Ecosystem', 'Lender Match', 'Shortlist']
  },

  funding_data_room: {
    id: 'funding_data_room',
    name: 'Funding Data Room Copilot',
    category: 'document collection',
    workflowStage: 4,
    description: 'Secure, client-facing document repository with automated checklist tracking and naming conventions.',
    bestFor: 'Eliminating email attachment chaos and standardizing file packages for lenders.',
    notFor: 'Public unencrypted file sharing.',
    pricingTier: 'Mid ($50-$250)',
    websiteUrl: 'https://tools.distilledfunding.com',
    isAffiliate: false,
    moonshineAsset: true,
    capability: 'Controlled deal data room & automated checklist progression',
    aiRole: 'Auto-categorize uploaded statements, flag missing months, and enforce naming standards',
    humanRole: 'Inspect flagged discrepancies and authorize lender package release',
    alternatives: ['docsumo', 'heron_data'],
    tags: ['Moonshine Ecosystem', 'Data Room', 'Documents']
  },

  funding_applicant_os: {
    id: 'funding_applicant_os',
    name: 'Funding Applicant OS',
    category: 'partner management',
    workflowStage: 2,
    description: 'White-labeled applicant operations engine connecting intake forms to CRM dedupe and stage updates.',
    bestFor: 'Platforms, agencies, and advisors embedding capital capabilities into their client ecosystem.',
    notFor: 'Direct retail borrowing without partner layer.',
    pricingTier: 'Pro ($250-$750)',
    websiteUrl: 'https://tools.distilledfunding.com',
    isAffiliate: false,
    moonshineAsset: true,
    capability: 'Embedded applicant pipeline & partner attribution preservation',
    aiRole: 'Parse incoming applicant payload, dedupe contact, and initiate CRM pipeline flow',
    humanRole: 'Handle high-touch client consulting and relationship ownership',
    alternatives: ['partner_intake_os'],
    tags: ['Moonshine Ecosystem', 'Applicant OS', 'Embedded Capital']
  },

  partner_intake_os: {
    id: 'partner_intake_os',
    name: 'Partner Intake OS',
    category: 'partner management',
    workflowStage: 1,
    description: 'Referral partner portal with automated tracking, lead attribution, and status visibility.',
    bestFor: 'Funding originators managing networks of CPAs, advisors, brokers, and affiliates.',
    notFor: 'Single-operator solo direct prospecting.',
    pricingTier: 'Mid ($50-$250)',
    websiteUrl: 'https://tools.distilledfunding.com',
    isAffiliate: false,
    moonshineAsset: true,
    capability: 'Referral attribution tracking & partner visibility portal',
    aiRole: 'Automate partner status digests and milestone alerts upon deal movement',
    humanRole: 'Cultivate partner relationships and structure revenue-sharing terms',
    alternatives: ['funding_applicant_os'],
    tags: ['Moonshine Ecosystem', 'Partner Portal', 'Attribution']
  },

  ai_agent_arsenal: {
    id: 'ai_agent_arsenal',
    name: 'AI Agent Arsenal',
    category: 'AI agents',
    workflowStage: 7,
    description: 'Curated repository of prompt architectures, review checkpoints, and operational workflows for capital teams.',
    bestFor: 'Teams scaling deal packaging, research briefings, and event-based follow-up.',
    notFor: 'Unmonitored autonomous execution.',
    pricingTier: 'Pro ($250-$750)',
    websiteUrl: 'https://tools.distilledfunding.com',
    isAffiliate: false,
    moonshineAsset: true,
    capability: 'Pre-configured capital operation agents & prompt guardrails',
    aiRole: 'Standardize agent workflows across deal research, packaging, and triage',
    humanRole: 'Audit agent outputs against human checkpoint matrix',
    alternatives: ['n8n', 'claude_ai'],
    tags: ['Moonshine Ecosystem', 'Agent Workflows', 'Guardrails']
  },

  resource_grid: {
    id: 'resource_grid',
    name: 'ResourceGrid by Moonshine',
    category: 'analytics',
    workflowStage: 8,
    description: 'Central knowledge repository, lender matrix documentation, and commercial finance operating templates.',
    bestFor: 'Training new originators and establishing standardized team SOPs.',
    notFor: 'Active CRM transaction management.',
    pricingTier: 'Free / Low',
    websiteUrl: 'https://tools.distilledfunding.com',
    isAffiliate: false,
    moonshineAsset: true,
    capability: 'Operational knowledge base & lender SOP library',
    aiRole: 'Search internal documentation and guidelines on demand',
    humanRole: 'Update program criteria as lender capital appetite shifts',
    alternatives: ['notion_ops'],
    tags: ['Moonshine Ecosystem', 'Knowledge Base', 'SOPs']
  }
};

export const TOOLS_CATALOG: ToolItem[] = Object.values(TOOLS_REGISTRY);
